### ISSUE TITLE
Error en compilar dir3caib

### ISSUE THREAD

**Issue by acuevas-dgtic** [GovernIB/projectebase#88]
Durant la compilació d'un projecte amb el perfil dir3caib apareix un error;

```
[INFO] ------< es.caib.projectebaseexemple:projectebaseexemple-dir3caib >------
[INFO] Building ProjecteBaseExemple - DIR3CAIB 1.0.0                    [12/14]
[INFO] --------------------------------[ war ]---------------------------------
[INFO]
[INFO] --- maven-clean-plugin:3.1.0:clean (default-clean) @ projectebaseexemple-dir3caib ---
[INFO] Deleting C:\Desarrollo\projectebaseexemple\projectebaseexemple-dir3caib\target
[INFO]
[INFO] --- maven-enforcer-plugin:3.0.0-M3:enforce (default) @ projectebaseexemple-dir3caib ---
[INFO]
[INFO] --- maven-resources-plugin:3.1.0:resources (default-resources) @ projectebaseexemple-dir3caib ---
[INFO] Using 'UTF-8' encoding to copy filtered resources.
[INFO] Copying 1 resource
[INFO]
[INFO] --- maven-compiler-plugin:3.8.1:compile (default-compile) @ projectebaseexemple-dir3caib ---
[INFO] Changes detected - recompiling the module!
[INFO] Compiling 8 source files to C:\Desarrollo\projectebaseexemple\projectebaseexemple-dir3caib\target\classes
compiler message file broken: key=compiler.misc.msg.bug arguments=11, {1}, {2}, {3}, {4}, {5}, {6}, {7}
java.lang.NullPointerException
        at jdk.compiler/com.sun.tools.javac.comp.Flow$FlowAnalyzer.visitApply(Flow.java:1235)
        at jdk.compiler/com.sun.tools.javac.tree.JCTree$JCMethodInvocation.accept(JCTree.java:1634)
        at jdk.compiler/com.sun.tools.javac.tree.TreeScanner.scan(TreeScanner.java:49)
        at jdk.compiler/com.sun.tools.javac.comp.Flow$BaseAnalyzer.scan(Flow.java:398)
        at jdk.compiler/com.sun.tools.javac.comp.Flow$FlowAnalyzer.visitReturn(Flow.java:1210)
        at jdk.compiler/com.sun.tools.javac.tree.JCTree$JCReturn.accept(JCTree.java:1546)
        at jdk.compiler/com.sun.tools.javac.tree.TreeScanner.scan(TreeScanner.java:49)
        at jdk.compiler/com.sun.tools.javac.comp.Flow$BaseAnalyzer.scan(Flow.java:398)
        at jdk.compiler/com.sun.tools.javac.tree.TreeScanner.scan(TreeScanner.java:57)
        at jdk.compiler/com.sun.tools.javac.comp.Flow$FlowAnalyzer.visitBlock(Flow.java:997)
        at jdk.compiler/com.sun.tools.javac.tree.JCTree$JCBlock.accept(JCTree.java:1020)
        at jdk.compiler/com.sun.tools.javac.tree.TreeScanner.scan(TreeScanner.java:49)
        at jdk.compiler/com.sun.tools.javac.comp.Flow$BaseAnalyzer.scan(Flow.java:398)
        at jdk.compiler/com.sun.tools.javac.comp.Flow$FlowAnalyzer.visitMethodDef(Flow.java:964)
        at jdk.compiler/com.sun.tools.javac.tree.JCTree$JCMethodDecl.accept(JCTree.java:866)
        at jdk.compiler/com.sun.tools.javac.tree.TreeScanner.scan(TreeScanner.java:49)
        at jdk.compiler/com.sun.tools.javac.comp.Flow$BaseAnalyzer.scan(Flow.java:398)
        at jdk.compiler/com.sun.tools.javac.comp.Flow$FlowAnalyzer.visitClassDef(Flow.java:927)
        at jdk.compiler/com.sun.tools.javac.tree.JCTree$JCClassDecl.accept(JCTree.java:774)
        at jdk.compiler/com.sun.tools.javac.tree.TreeScanner.scan(TreeScanner.java:49)
        at jdk.compiler/com.sun.tools.javac.comp.Flow$BaseAnalyzer.scan(Flow.java:398)
        at jdk.compiler/com.sun.tools.javac.comp.Flow$FlowAnalyzer.analyzeTree(Flow.java:1327)
        at jdk.compiler/com.sun.tools.javac.comp.Flow$FlowAnalyzer.analyzeTree(Flow.java:1317)
        at jdk.compiler/com.sun.tools.javac.comp.Flow.analyzeTree(Flow.java:218)
        at jdk.compiler/com.sun.tools.javac.main.JavaCompiler.flow(JavaCompiler.java:1401)
        at jdk.compiler/com.sun.tools.javac.main.JavaCompiler.flow(JavaCompiler.java:1375)
        at jdk.compiler/com.sun.tools.javac.main.JavaCompiler.compile(JavaCompiler.java:973)
        at jdk.compiler/com.sun.tools.javac.api.JavacTaskImpl.lambda$doCall$0(JavacTaskImpl.java:104)
        at jdk.compiler/com.sun.tools.javac.api.JavacTaskImpl.handleExceptions(JavacTaskImpl.java:147)
        at jdk.compiler/com.sun.tools.javac.api.JavacTaskImpl.doCall(JavacTaskImpl.java:100)
        at jdk.compiler/com.sun.tools.javac.api.JavacTaskImpl.call(JavacTaskImpl.java:94)
        at org.codehaus.plexus.compiler.javac.JavaxToolsCompiler.compileInProcess(JavaxToolsCompiler.java:126)
        at org.codehaus.plexus.compiler.javac.JavacCompiler.performCompile(JavacCompiler.java:174)
        at org.apache.maven.plugin.compiler.AbstractCompilerMojo.execute(AbstractCompilerMojo.java:1134)
        at org.apache.maven.plugin.compiler.CompilerMojo.execute(CompilerMojo.java:187)
        at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:137)
        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:210)
        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:156)
        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:148)
        at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:117)
        at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:81)
        at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build(SingleThreadedBuilder.java:56)
        at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:128)
        at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:305)
        at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:192)
        at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:105)
        at org.apache.maven.cli.MavenCli.execute(MavenCli.java:957)
        at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:289)
        at org.apache.maven.cli.MavenCli.main(MavenCli.java:193)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:566)
        at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:282)
        at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:225)
        at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:406)
        at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:347)
[INFO] -------------------------------------------------------------
[ERROR] COMPILATION ERROR :
[INFO] -------------------------------------------------------------
[ERROR] An unknown compilation problem occurred
[INFO] 1 error
[INFO] -------------------------------------------------------------
[INFO] ------------------------------------------------------------------------
[INFO] Reactor Summary for ProjecteBaseExemple 1.0.0:
[INFO]
[INFO] ProjecteBaseExemple ................................ SUCCESS [  0.432 s]
[INFO] ProjecteBaseExemple - COMMONS ...................... SUCCESS [  2.107 s]
[INFO] ProjecteBaseExemple - PERSISTENCE .................. SUCCESS [  0.925 s]
[INFO] ProjecteBaseExemple - EJB .......................... SUCCESS [  0.587 s]
[INFO] ProjecteBaseExemple - BACK ......................... SUCCESS [  1.759 s]
[INFO] ProjecteBaseExemple - FRONT ........................ SUCCESS [  0.301 s]
[INFO] ProjecteBaseExemple - REST - API ................... SUCCESS [  1.326 s]
[INFO] projectebaseexemple-apifirmasimple ................. SUCCESS [  1.371 s]
[INFO] ProjecteBaseExemple - ARXIU ........................ SUCCESS [  0.648 s]
[INFO] ProjecteBaseExemple - REGISTRE ..................... SUCCESS [  0.416 s]
[INFO] ProjecteBaseExemple - NOTIB ........................ SUCCESS [  0.568 s]
[INFO] ProjecteBaseExemple - DIR3CAIB ..................... FAILURE [  0.315 s]
[INFO] ProjecteBaseExemple - DISTRIBUCIO .................. SKIPPED
[INFO] ProjecteBaseExemple - EAR .......................... SKIPPED
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  11.103 s
[INFO] Finished at: 2020-09-22T11:33:35+02:00
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.8.1:compile (default-compile) on project projectebaseexemple-dir3caib: Compilation failure
[ERROR] An unknown compilation problem occurred
[ERROR]
[ERROR] -> [Help 1]
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoFailureException
[ERROR]
[ERROR] After correcting the problems, you can resume the build with the command
[ERROR]   mvn <args> -rf :projectebaseexemple-dir3caib
```

**Comment by areus-fundaciobit** [comment]
Sembla que es tractaria d'un bug al JDK: https://bugs.openjdk.java.net/browse/JDK-8203913
No aconseguesc trobar però a partir de quina versió del java 11 està arreglat, en qualsevol cas, amb l'actual 11.0.8 compila correctament.

**Comment by acuevas-dgtic** [comment]
S'ha executat amb la openjdk-11+28 disponible a https://jdk.java.net/java-se-ri/11
![imatge](https://user-images.githubusercontent.com/58417501/93872461-80a64980-fcd0-11ea-8c1c-09679a9a406d.png)

**Comment by areus-fundaciobit** [comment]
Ok. Aquesta és la release inicial de java 11 de setembre de 2018, equivaldria a la 11.0.0

El jdk de referència només el mantengueren fins la 11.0.2 que es pot trobar [aquí](https://jdk.java.net/archive/) però encara té l'error. 

Pel que he pogut comprovar, al [JDK distribuït per Oracle](https://www.oracle.com/java/technologies/javase-jdk11-downloads.html), aquesta issue no s'ha solucionat fins al JDK més recent, el 11.0.8 de juliol de 2020.

Mentre que amb els [JDK distribuïts per AdoptOpenJDK](https://adoptopenjdk.net/archive.html) a partir de la versió 11.0.4+11 (de juliol de 2019) ja estava solucionat.

projectebase empra el `maven-enforcer-plugin` per garantir que l'entorn és el correcte (versions maven, java...), i actualment la versió mínima del jdk està posat a 11, que equival a 11.0.0. Podríem fixar 11.0.8, i així si s'intenta compilar amb una release de java 11 més antiga avisarà de que cal com a mínim la 11.0.8.

**Comment by acuevas-dgtic** [comment]
Si esto solo pasa con el perfil de dir3, ¿no se podria modificar el código de la integración para evitar el error? Asi evitamos que los desarrolladores tengan que actualizarse el entorno de desarrollo

**Comment by areus-fundaciobit** [comment]
Veig que el problema el dona una sèrie de construccions d'aquest tipus `new GenericType<>() {}` que hi ha dins el client REST de Dir3Caib, a mètdoes com aquest:

    @Override
    public List<CodigoValor> comunidadesAutonomas() {
        return client.target(baseUrl + CATALOGO_COMUNIDADES_AUTONOMAS)
                .request(MediaType.APPLICATION_JSON)
                .get(new GenericType<>() {}); 
    }

Es fàcil canviar-ho afegint el tipus el tipus explícitament encara que no calgui.

    @Override
    public List<CodigoValor> comunidadesAutonomas() {
        return client.target(baseUrl + CATALOGO_COMUNIDADES_AUTONOMAS)
                .request(MediaType.APPLICATION_JSON)
                .get(new GenericType<List<CodigoValor>>() {});
    }

Ho he provat i així la compilació funciona amb la versió 11+28 RI.

D'altra banda, no actualitzar l'entorn també té un perill. Si a qualcú mirant el codi se li ocorr suprimir el tipus explicit (l'IntelliJ mateix me marca un warning on aconsella canviar `<List<CodigoValor>` per `<>`), li començarà a sortir aquest error i potser no vegi d'on li ve, perquè l'error no dona detalls de res.

![imatge](https://user-images.githubusercontent.com/49397053/93879935-ebf61880-fcdc-11ea-8bd6-c9751af358a5.png)

**Comment by acuevas-dgtic** [comment]
Ok haz el cambio. Atualizaremos la guia de desarrollo amb el JDK distribuïts per AdoptOpenJDK a partir de la versió 11.0.4+11
